# Generated by Django 4.2.6 on 2023-11-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('popularity_index', models.FloatField()),
                ('word_cloud_text', models.TextField()),
            ],
        ),
    ]
